#!/usr/bin/env python

try:
    from switzerland.client import Alice
except ImportError:
    import sys
    sys.path.append('/usr/local/lib/python2.5/site-packages/')
    sys.path.append('/usr/lib/python2.5/site-packages/')
    sys.path.append('.')

    try:
        from switzerland.client import Alice
    except ImportError, ie:
        print >> sys.stderr, \
              ie.message
        print >> sys.stderr, \
              'Error: cannot load client. Please check your $PYTHONPATH.'
        sys.exit(1)

try:
    Alice.main()
except KeyboardInterrupt:
    pass
