#!/usr/bin/env python2.5

try:
  from switzerland.server import Switzerland
except ImportError:
  import sys
  sys.path.append("/usr/local/lib/python2.5/site-packages/")
  sys.path.append("/usr/lib/python2.5/site-packages/")
  sys.path.append(".")
  from switzerland.server import Switzerland

Switzerland.main()
