#!/usr/bin/env python2.5

try:
    from switzerland.client import Alice
except ImportError:
    import sys
    sys.path.append('/usr/local/lib/python2.5/site-packages/')
    sys.path.append('/usr/lib/python2.5/site-packages/')
    sys.path.append('.')

    try:
        from switzerland.client import Alice
    except ImportError:
        print >> sys.stderr, \
              'Error: cannot load client. Please check your $PYTHONPATH.'
        sys.exit(1)

Alice.main()
